name: aicp
description: App AICP

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.6+1
#  flutter build appbundle --build-number=6 --build-name=1.0.6 --no-sound-null-safety



environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  http: ^0.13.4
  provider: ^6.0.2
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.13
  open_appstore: ^1.0.2
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.18
  flutter_appavailability: ^0.0.21
  package_info: ^2.0.2
  global_configuration: 2.0.0-nullsafety.1
  easy_localization: ^3.0.0
  flutter_svg: ^0.23.0+1
  flutter_screenutil: ^5.2.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  font_awesome_flutter: ^9.2.0
  intl_phone_number_input: ^0.7.0+2
  pin_input_text_field: ^4.1.1
  flutter_countdown_timer: ^4.1.0
  cached_network_image: ^3.2.0
  pull_to_refresh: ^2.0.0
  loading_indicator: ^3.0.2
  flutter_easyloading: ^3.0.3
  flutter_spinkit: ^5.1.0
  syncfusion_flutter_sliders: ^19.4.50
  auto_size_text: ^3.0.0
  page_transition: ^2.0.5
  device_info_plus: ^3.2.2
  flutter_phoenix: ^1.0.0
  firebase_messaging: ^11.1.0
  firebase_core: ^1.3.0
  flutter_app_badger: ^1.3.0
  modal_bottom_sheet: ^2.0.0
  image_picker: ^0.8.3+2
  readmore: ^2.1.0
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app icon_1024x1024.png"

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/translate/
    - assets/cert/
    - assets/fonts/
    - assets/icon/
    - assets/images/
    - assets/images/splash_screen/
    - assets/images/profile/
    - assets/images/MR/
    - assets/images/logo/
    - assets/images/home/
    - assets/images/feedback/
    - assets/images/product/

  fonts:
    - family: Prompt-Black
      fonts:
        - asset: assets/fonts/Prompt-Black.ttf
    - family: Prompt-BlackItalic
      fonts:
        - asset: assets/fonts/Prompt-BlackItalic.ttf
    - family: Prompt-Bold
      fonts:
        - asset: assets/fonts/Prompt-Bold.ttf
    - family: Prompt-BoldItalic
      fonts:
        - asset: assets/fonts/Prompt-BoldItalic.ttf
    - family: Prompt-ExtraBold
      fonts:
        - asset: assets/fonts/Prompt-ExtraBold.ttf
    - family: Prompt-ExtraBoldItalic
      fonts:
        - asset: assets/fonts/Prompt-ExtraBoldItalic.ttf
    - family: Prompt-ExtraLight
      fonts:
        - asset: assets/fonts/Prompt-ExtraLight.ttf
    - family: Prompt-ExtraLightItalic
      fonts:
        - asset: assets/fonts/Prompt-ExtraLightItalic.ttf
    - family: Prompt-Light
      fonts:
        - asset: assets/fonts/Prompt-Light.ttf
    - family: Prompt-LightItalic
      fonts:
        - asset: assets/fonts/Prompt-LightItalic.ttf
    - family: Prompt-Medium
      fonts:
        - asset: assets/fonts/Prompt-Medium.ttf
    - family: Prompt-MediumItalic
      fonts:
        - asset: assets/fonts/Prompt-MediumItalic.ttf
    - family: Prompt-Regular
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
    - family: Prompt-RegularItalic
      fonts:
        - asset: assets/fonts/Prompt-RegularItalic.ttf
    - family: Prompt-SemiBold
      fonts:
        - asset: assets/fonts/Prompt-SemiBold.ttf
    - family: Prompt-SemiBoldItalic
      fonts:
        - asset: assets/fonts/Prompt-SemiBoldItalic.ttf
    - family: Prompt-Thin
      fonts:
        - asset: assets/fonts/Prompt-Thin.ttf
    - family: Prompt-ThinItalic
      fonts:
        - asset: assets/fonts/Prompt-ThinItalic.ttf